SET(_CPS_FUTURE_REQUIRED_VARS  CPS_FUTURE_INCLUDE_DIR CPS_FUTURE_LIBRARY )

FIND_PATH(
	CPS_FUTURE_INCLUDE_DIR
	NAMES cps/future.h
    HINTS ${CPS_FUTURE_DIR}/include
)

FIND_LIBRARY(
	CPS_FUTURE_LIBRARY
	NAMES cps-future
    HINTS ${CPS_FUTURE_DIR}/lib
)

SET(CPS_FUTURE_PROCESS_INCLUDES CPS_FUTURE_INCLUDE_DIR)
SET(CPS_FUTURE_PROCESS_LIBS CPS_FUTURE_LIBRARY)

include(FindPackageHandleStandardArgs)
FIND_PACKAGE_HANDLE_STANDARD_ARGS(
	CPS_FUTURE
	DEFAULT_MSG
	${_CPS_FUTURE_REQUIRED_VARS}
)

